# Generated by Django 4.2.10 on 2024-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='target_text',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='translation',
            name='source_text',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='translation',
            name='target_language',
            field=models.CharField(max_length=200),
        ),
    ]
